### ISSUE TITLE
ReferenceError: epk is not defined

### ISSUE THREAD

**Issue by agrozyme** [tibetty/ecies-lite#1]
index.js line 71: ReferenceError: epk is not defined
`let hash = crypto.createHash('sha256').update(ecdh.computeSecret(epk)).digest();`

**Comment by tibetty** [comment]
Can you dump the *body* argument passed to the **decrypt** method? *epk* should be a member of *body*, and if the body is returned from **encrypt**, it will be included.

**Comment by agrozyme** [comment]
I try with a new test case, it is OK.
the result of encrypt has epk.

**Comment by tibetty** [comment]
Good! You can browserify it and use this simple toolkit in browser environment as well. Let me know if you meet any new problem.
